# Python code to demonstrate the Exception of
# log(a)

import math

# Printing the log(a) of -14
# Throws Exception
print ("log(a) value of -14 is : ", end="")
print (math.log(-14))
